<map version="0.9.0"><attribute_registry SHOW_ATTRIBUTES="hide"/>
<node TEXT="Context Model&#10;&#10;Gazebo Hub Project&#10;&#10;27 May 2013" ID="Freemind_Link_1"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /><node TEXT="Human Enterprise" ID="Freemind_Link_2"  POSITION="right"  COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /><node TEXT="Society" ID="Freemind_Link_3"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /><node TEXT="Community" ID="Freemind_Link_4"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /><node TEXT="Community&#10;(Concepts)&#10;&#10;Draft 2, 23 Feb 2013&#10;&#10;(Non-Normative)" ID="Freemind_Link_5"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /><node TEXT="Works Referenced" ID="Freemind_Link_6"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /><node TEXT="See also: Bibliographies in those works" ID="Freemind_Link_8"   COLOR="#000000" BACKGROUND_COLOR="#FFD9B2" STYLE="bubble" ><edge COLOR="#FFD9B2" /><attribute NAME="Callout" VALUE="{216, -140}"/></node>
<node TEXT="[Goodman1998]&#10;&#10;Goodman, R. M. et al. &#x201c;Identifying and Defining the Dimensions of Community Capacity to Provide a Basis for Measurement.&#x201d; Health Education &amp; Behavior 25.3 (1998): 258&#x2013;278. " ID="Freemind_Link_7" LINK="http://www.mendeley.com/catalog/identifying-defining-dimensions-community-capacity-provide-basis-measurement/"  COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /></node>
</node>
<node TEXT="This section of the context model was recently added from within a personal outline of selected community concepts. It's currently peppered with my own commentary, in outline callouts. The community concepts model should soon be updated towards a more normative form, now that it would be included in the formal Context Model for the Gazebo Hub Project&#10;- Sean Champ, 27 May 2013" ID="Freemind_Link_79"   COLOR="#000000" BACKGROUND_COLOR="#FFD9B2" STYLE="bubble" ><edge COLOR="#FFD9B2" /><attribute NAME="Callout" VALUE="{-198, -225}"/></node>
<node TEXT="Concepts&#10;&#10;(Current Draft)" ID="Freemind_Link_9"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /><node TEXT="Community Capacity" ID="Freemind_Link_10"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /><node TEXT="Dimensions&#10;&#10;[Goodman1998]" ID="Freemind_Link_11"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /><node TEXT="Participation &amp; Leadership" ID="Freemind_Link_12"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /><node TEXT="Citizen Participation" ID="Freemind_Link_13"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /><node TEXT="Strengths in the participant base" ID="Freemind_Link_14"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /></node>
<node TEXT="Diversity in networks" ID="Freemind_Link_15"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /><node TEXT="I'll add: Stability in networks" ID="Freemind_Link_16"   COLOR="#000000" BACKGROUND_COLOR="#FFD9B2" STYLE="bubble" ><edge COLOR="#FFD9B2" /><font BOLD="false" ITALIC="false" SIZE="14"/><attribute NAME="Callout" VALUE="{279, -10}"/></node>
</node>
<node TEXT="Citizen involvement in defining, understanding, and completing goals " ID="Freemind_Link_17"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /><node TEXT="I'll add: Community goals setting should be community driven, in a democratic society " ID="Freemind_Link_18"   COLOR="#000000" BACKGROUND_COLOR="#FFD9B2" STYLE="bubble" ><edge COLOR="#FFD9B2" /><font BOLD="false" ITALIC="false" SIZE="14"/><attribute NAME="Callout" VALUE="{511, -49}"/></node>
</node>
</node>
<node TEXT="Leadership" ID="Freemind_Link_19"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /><node TEXT="Formal and informal leaders should be included" ID="Freemind_Link_20"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /></node>
<node TEXT="Leadership provides some sense of direction and structure " ID="Freemind_Link_21"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /><node TEXT="I'll add: Leadership brings its own experiences to the table. Furthermore, it should be emphasized as a matter of, by, and for the people, not per se for the agendas of community leadership if apart from the goals of the community " ID="Freemind_Link_22"   COLOR="#000000" BACKGROUND_COLOR="#FFD9B2" STYLE="bubble" ><edge COLOR="#FFD9B2" /><font BOLD="false" ITALIC="false" SIZE="14"/><attribute NAME="Callout" VALUE="{523, -40}"/></node>
</node>
<node TEXT="Leadership must encourage participation from and within the diverse community base" ID="Freemind_Link_23"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /><node TEXT="Procedures may be implemented (insofar as developed) to endeavor to ensure (and support) an inclusive mode of participation during group meetings and events" ID="Freemind_Link_24"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /><node TEXT="I'll add: But try not to  make it like a dog and pony show, of structure devoid of substantive meaning and understanding" ID="Freemind_Link_25"   COLOR="#000000" BACKGROUND_COLOR="#FFD9B2" STYLE="bubble" ><edge COLOR="#FFD9B2" /><font BOLD="false" ITALIC="false" SIZE="14"/><attribute NAME="Callout" VALUE="{407, -5}"/></node>
</node>
</node>
<node TEXT="Leadership must assist in sharing information about resources among community and organizational participants" ID="Freemind_Link_26"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /></node>
<node TEXT="Must assist in developing new leaders " ID="Freemind_Link_27"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /></node>
<node TEXT="Must be responsive and accessible in demeanor" ID="Freemind_Link_28"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /></node>
<node TEXT="Not disconnected from other leaders" ID="Freemind_Link_29"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /></node>
</node>
</node>
<node TEXT="Skills" ID="Freemind_Link_30"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /><node TEXT="The authors seem to propose a rather formal approach to community activity, in terms of skills - no doubt, an approach influenced with paradigms of social policy work. &#10;&#10;Experience may hold that a less formal, less bureaucratic approach may ultimately serve to be more adaptive and more sincerely effective, in addressing community needs, goals, and community life overall, with available, material resources. &#10;&#10;Perhaps an informal approach, as such, may serve to augment the necessarily formalized approaches of social policy workers " ID="Freemind_Link_31"   COLOR="#000000" BACKGROUND_COLOR="#FFD9B2" STYLE="bubble" ><edge COLOR="#FFD9B2" /><font BOLD="false" ITALIC="false" SIZE="10"/><attribute NAME="Callout" VALUE="{909, 9}"/></node>
</node>
<node TEXT="Resources" ID="Freemind_Link_32"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /><node TEXT="May be internal or external to a community, as resources " ID="Freemind_Link_33"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /></node>
<node TEXT="Resource sharing, in the community" ID="Freemind_Link_34"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /></node>
<node TEXT="Social capital" ID="Freemind_Link_35"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /><node TEXT="Trust" ID="Freemind_Link_36"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /></node>
<node TEXT="Confidence" ID="Freemind_Link_37"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /></node>
<node TEXT="Cooperation" ID="Freemind_Link_38"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /></node>
</node>
</node>
<node TEXT="Social and Interorganizational Networks" ID="Freemind_Link_39"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /><node TEXT="Reciprocal links" ID="Freemind_Link_40"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /></node>
<node TEXT="Frequency of supportive interactions" ID="Freemind_Link_41"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /></node>
<node TEXT="Overlap, among community networks" ID="Freemind_Link_42"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /><node TEXT="May exist as social, pragmatic, and/or conceptual overlap, for instance " ID="Freemind_Link_43"   COLOR="#000000" BACKGROUND_COLOR="#FFD9B2" STYLE="bubble" ><edge COLOR="#FFD9B2" /><font BOLD="false" ITALIC="false" SIZE="14"/><attribute NAME="Callout" VALUE="{453, -7}"/></node>
</node>
<node TEXT="Members able to form new associations " ID="Freemind_Link_44"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /><node TEXT="A democratic structure for community, not oligarchical" ID="Freemind_Link_45"   COLOR="#000000" BACKGROUND_COLOR="#FFD9B2" STYLE="bubble" ><edge COLOR="#FFD9B2" /><font BOLD="false" ITALIC="false" SIZE="14"/><attribute NAME="Callout" VALUE="{475, 6}"/></node>
</node>
<node TEXT="Cooperative decision-making " ID="Freemind_Link_46"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /></node>
</node>
<node TEXT="Sense of Community" ID="Freemind_Link_47"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /><node TEXT="Concern for community issues " ID="Freemind_Link_48"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /><node TEXT="Must be predicated with an understanding of community issues" ID="Freemind_Link_49"   COLOR="#000000" BACKGROUND_COLOR="#FFD9B2" STYLE="bubble" ><edge COLOR="#FFD9B2" /><font BOLD="false" ITALIC="false" SIZE="14"/><attribute NAME="Callout" VALUE="{431, 3}"/></node>
</node>
<node TEXT="Respect" ID="Freemind_Link_50"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /></node>
<node TEXT="Generosity" ID="Freemind_Link_51"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /></node>
<node TEXT="Selflessness" ID="Freemind_Link_52"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /></node>
<node TEXT="Connectedness with place and people" ID="Freemind_Link_53"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /></node>
<node TEXT="Needs fulfillment through membership &#10;(???)" ID="Freemind_Link_54"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /><node TEXT="This one is listed in [Goodman1998] table 1&#10;&#10;It needs more exposition than in table 1 - refer to later sections of the paper" ID="Freemind_Link_55"   COLOR="#000000" BACKGROUND_COLOR="#FFD9B2" STYLE="bubble" ><edge COLOR="#FFD9B2" /><font BOLD="false" ITALIC="false" SIZE="14"/><attribute NAME="Callout" VALUE="{440, -17}"/></node>
</node>
</node>
<node TEXT="Understanding of Community History" ID="Freemind_Link_56"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /><node TEXT="Recent and historic social, political, and economic changes " ID="Freemind_Link_57"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /></node>
<node TEXT="Knowledge of organizations, community groups, and community sections" ID="Freemind_Link_58"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /><node TEXT="The community may endeavor to ensure that community leadership would not displace selected groups, if by way of negligence and alternate focus" ID="Freemind_Link_59"   COLOR="#000000" BACKGROUND_COLOR="#FFD9B2" STYLE="bubble" ><edge COLOR="#FFD9B2" /><font BOLD="false" ITALIC="false" SIZE="14"/><attribute NAME="Callout" VALUE="{437, -4}"/></node>
</node>
<node TEXT="Community relations to other communities" ID="Freemind_Link_60"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /></node>
</node>
<node TEXT="Community Power" ID="Freemind_Link_61"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /><node TEXT="Positions in regards to dynamics of change - to create, support or resist change - in regards to community resources, community interests (and goals), and community experiences " ID="Freemind_Link_62"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /></node>
<node TEXT="Mutual power, not controlling power" ID="Freemind_Link_63"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /><node TEXT="Avoid &quot;zero sum&quot; strategies" ID="Freemind_Link_64"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /></node>
</node>
<node TEXT="Diversity of influences" ID="Freemind_Link_65"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /></node>
</node>
<node TEXT="Community Values" ID="Freemind_Link_66"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /><node TEXT="Consensus building " ID="Freemind_Link_67"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /></node>
<node TEXT="&quot;Norms, standards, and attributes&quot;" ID="Freemind_Link_68"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /><node TEXT="This concept may support a risk, however, of introducing private agendas in endeavoring to override community interests" ID="Freemind_Link_69"   COLOR="#000000" BACKGROUND_COLOR="#FFD9B2" STYLE="bubble" ><edge COLOR="#FFD9B2" /><font BOLD="false" ITALIC="false" SIZE="14"/><attribute NAME="Callout" VALUE="{416, -8}"/></node>
</node>
</node>
<node TEXT="Critical Reflection" ID="Freemind_Link_70"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /><node TEXT="Reflection on assumptions about ideas and actions" ID="Freemind_Link_71"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /></node>
<node TEXT="Logical reasoning  and scrutiny in regards to ambiguity in community discussions" ID="Freemind_Link_72"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /><node TEXT="This may entail a sense of patience and of clarity, in regards to difficulties in communication and mutual understanding of ideas " ID="Freemind_Link_73"   COLOR="#000000" BACKGROUND_COLOR="#FFD9B2" STYLE="bubble" ><edge COLOR="#FFD9B2" /><font BOLD="false" ITALIC="false" SIZE="14"/><attribute NAME="Callout" VALUE="{432, -3}"/></node>
</node>
<node TEXT="Understanding pressures of environmental influence on individual and social behavior" ID="Freemind_Link_74"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /><node TEXT="This may call for a sense of caring objectivity, about environmental influences - even in regards to negative trends in a community, trends such as of youth gangs, violence, aggression, drug use, sexual abuse, homelessness, poverty, and overall difficulty in overcoming the negative influences of the diaspora, in personal and family life. while (for instance) proceeding through school, individually and within the community, and in living in professional and family life, overall." ID="Freemind_Link_75"   COLOR="#000000" BACKGROUND_COLOR="#FFD9B2" STYLE="bubble" ><edge COLOR="#FFD9B2" /><font BOLD="false" ITALIC="false" SIZE="14"/><attribute NAME="Callout" VALUE="{777, 15}"/></node>
</node>
<node TEXT="Self-analysis and evolution in the community" ID="Freemind_Link_76"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /></node>
</node>
</node>
</node>
</node>
<node TEXT="Works remaining to reference" ID="Freemind_Link_77"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /><node TEXT="[Young1995]&#10;&#10;Young, Iris M. &#x201c;The Ideal of Community and the Politics of Difference.&#x201d; Feminism &amp; Community. Ed. Penny A Weiss &amp; Marilyn Friedman. Philadelphia: Temple University Press, 1995. 233&#x2013;258." ID="Freemind_Link_78" LINK="http://books.google.com/books?hl=en&amp;lr=&amp;id=63J-U6N2THYC&amp;oi=fnd&amp;pg=PA233&amp;ots=kB_r3Aedf6&amp;sig=LzW8bWEaz1aTuonXkeDtUVGOfHs#v=onepage&amp;q&amp;f=false"  COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /></node>
</node>
</node>
</node>
<node TEXT="Social Entrepreneurialism" ID="Freemind_Link_80"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /></node>
<node TEXT="Business" ID="Freemind_Link_81"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /><node TEXT="Work Area: Economic Analysis" ID="Freemind_Link_82"   COLOR="#000000" BACKGROUND_COLOR="#B2FFD9" STYLE="bubble" ><edge COLOR="#B2FFD9" /><node TEXT="Statistical Data Sets" ID="Freemind_Link_83"   COLOR="#000000" BACKGROUND_COLOR="#B2FFD9" STYLE="bubble" ><edge COLOR="#B2FFD9" /><node TEXT="BLS Consumer Spending Index" ID="Freemind_Link_84"   COLOR="#000000" BACKGROUND_COLOR="#B2FFD9" STYLE="bubble" ><edge COLOR="#B2FFD9" /></node>
<node TEXT="BLS Labor Data Sets" ID="Freemind_Link_85"   COLOR="#000000" BACKGROUND_COLOR="#B2FFD9" STYLE="bubble" ><edge COLOR="#B2FFD9" /></node>
</node>
<node TEXT="Presentation Models" ID="Freemind_Link_86"   COLOR="#000000" BACKGROUND_COLOR="#B2FFD9" STYLE="bubble" ><edge COLOR="#B2FFD9" /><node TEXT="uDig Projects" ID="Freemind_Link_87"   COLOR="#000000" BACKGROUND_COLOR="#B2FFD9" STYLE="bubble" ><edge COLOR="#B2FFD9" /></node>
<node TEXT="Online Presentation Models" ID="Freemind_Link_88"   COLOR="#000000" BACKGROUND_COLOR="#B2FFD9" STYLE="bubble" ><edge COLOR="#B2FFD9" /></node>
</node>
<node TEXT="Relevance" ID="Freemind_Link_89"   COLOR="#000000" BACKGROUND_COLOR="#B2FFD9" STYLE="bubble" ><edge COLOR="#B2FFD9" /><node TEXT="Consumer Market Analysis&#10;(Business View)" ID="Freemind_Link_90"   COLOR="#000000" BACKGROUND_COLOR="#B2FFD9" STYLE="bubble" ><edge COLOR="#B2FFD9" /></node>
<node TEXT="Jobs Market Analysis&#10;(Student View)" ID="Freemind_Link_91"   COLOR="#000000" BACKGROUND_COLOR="#B2FFD9" STYLE="bubble" ><edge COLOR="#B2FFD9" /></node>
</node>
<node TEXT="To do: Gazebo Hub Project Modeling (PM) Ontology&#10;&#10;Model the concept of a &quot;work area&quot; with an additional OWL class, in a project modeling ontology, such that would import the Gazebo Hub CM ontology&#10;&#10;Extend that &quot;work area&quot; class and its data model instance, &quot;Economic analysis,&quot; with properties associating a work area with developer resources  such as: Repository and module path; Wiki; Tickets. Also define a class, &quot;Project,&quot; in that ontology, and consider integrating the ontology with emForge.&#10;&#10;Note that a &quot;Work area&quot; may be informally like a module, whether or not discretely integrating with a containing system. A work area provides, simply, a context for further development of resources within a project.&#10;&#10;The class, &quot;Milestone,&quot; would extend, &quot;Work Area&quot;&#10;&#10;The PM ontology may also define a class, &quot;Roadmap&quot;" ID="Freemind_Link_92"   COLOR="#000000" BACKGROUND_COLOR="#FFD9B2" STYLE="bubble" ><edge COLOR="#FFD9B2" /><font BOLD="false" ITALIC="false" SIZE="14"/><attribute NAME="Callout" VALUE="{-86, 228}"/><node TEXT="This, in turn, may serve to suggest the development of some new project management tooling, incorporating data models based on the PM ontology" ID="Freemind_Link_93"   COLOR="#000000" BACKGROUND_COLOR="#FFD9B2" STYLE="bubble" ><edge COLOR="#FFD9B2" /><attribute NAME="Callout" VALUE="{-148, 253}"/><node TEXT="The Gazebo Hub Core Ontologies set should include an ontology for serialization of a permissions model, for use in ontology tooling. To serve a functional purpose, that ontology should also be incorporated with a user authentication model for integration with same tooling," ID="Freemind_Link_94"   COLOR="#000000" BACKGROUND_COLOR="#FFD9B2" STYLE="bubble" ><edge COLOR="#FFD9B2" /><attribute NAME="Callout" VALUE="{-21, 138}"/><node TEXT="This model may derive features from SAML" ID="Freemind_Link_95" LINK="http://en.wikipedia.org/wiki/SAML_1.1"  COLOR="#000000" BACKGROUND_COLOR="#FFD9B2" STYLE="bubble" ><edge COLOR="#FFD9B2" /><attribute NAME="Callout" VALUE="{384, -2}"/><node TEXT="JA-SIG CAS supports using SAML 1.1 for ticket validation requests" ID="Freemind_Link_96" LINK="https://wiki.jasig.org/plugins/servlet/mobile#content/view/6063483"  COLOR="#000000" BACKGROUND_COLOR="#FFD9B2" STYLE="bubble" ><edge COLOR="#FFD9B2" /><attribute NAME="Callout" VALUE="{17, -113}"/><node TEXT="See also: CAS user manual" ID="Freemind_Link_97" LINK="https://wiki.jasig.org/plugins/servlet/mobile#content/view/2424984"  COLOR="#000000" BACKGROUND_COLOR="#FFD9B2" STYLE="bubble" ><edge COLOR="#FFD9B2" /><attribute NAME="Callout" VALUE="{339, -2}"/></node>
</node>
</node>
<node TEXT="it may be wise to consider basing the auth/permissions model and corresponding system on a CAS system" ID="Freemind_Link_98"   COLOR="#000000" BACKGROUND_COLOR="#FFD9B2" STYLE="bubble" ><edge COLOR="#FFD9B2" /><attribute NAME="Callout" VALUE="{-53, 120}"/><node TEXT="See also: Notes for installing CAS in jBoss" ID="Freemind_Link_99" LINK="https://wiki.jasig.org/pages/viewpage.action?pageId=49251080"  COLOR="#000000" BACKGROUND_COLOR="#FFD9B2" STYLE="bubble" ><edge COLOR="#FFD9B2" /><attribute NAME="Callout" VALUE="{369, -38}"/></node>
<node TEXT="See also: CAS user manual" ID="Freemind_Link_100" LINK="https://wiki.jasig.org/plugins/servlet/mobile#content/view/2424984"  COLOR="#000000" BACKGROUND_COLOR="#FFD9B2" STYLE="bubble" ><edge COLOR="#FFD9B2" /><attribute NAME="Callout" VALUE="{298, 55}"/></node>
<node TEXT="Successful CAS installation would serve to enable the server as an SSO provider.&#10;&#10;Other more low-level authentication models are available (e.g PAM-LDAP)" ID="Freemind_Link_101"   COLOR="#000000" BACKGROUND_COLOR="#FFD9B2" STYLE="bubble" ><edge COLOR="#FFD9B2" /><attribute NAME="Callout" VALUE="{506, 201}"/></node>
</node>
</node>
</node>
</node>
</node>
</node>
</node>
<node TEXT="Technology" ID="Freemind_Link_102"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /><node TEXT="Software Programming" ID="Freemind_Link_103"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /><node TEXT="Software Languages" ID="Freemind_Link_104"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /><node TEXT="Systems Programming Languages" ID="Freemind_Link_105"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /><node TEXT="Lisp Programming Languages" ID="Freemind_Link_106"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /></node>
<node TEXT="Common Lisp Programming Language" ID="Freemind_Link_107"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /></node>
</node>
<node TEXT="Data Serialization Languages" ID="Freemind_Link_108"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /><node TEXT="XMI" ID="Freemind_Link_109"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /><arrowlink COLOR="#477DB2" DESTINATION="Freemind_Link_110" ENDARROW="Default" ENDINCLINATION="22;0;" ID="Arrow_ID_258" STARTARROW="None" STARTINCLINATION="22;0;" SOURCE_LABEL="" MIDDLE_LABEL="Derives From" TARGET_LABEL="" /></node>
<node TEXT="XML" ID="Freemind_Link_110"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /><arrowlink COLOR="#477DB2" DESTINATION="Freemind_Link_112" ENDARROW="Default" ENDINCLINATION="22;0;" ID="Arrow_ID_259" STARTARROW="None" STARTINCLINATION="22;0;" SOURCE_LABEL="" MIDDLE_LABEL="Derives From" TARGET_LABEL="" /><node TEXT="The variety of XML syntaxes presents the opportunity to illustrate the usage of a single mode of informative &quot;derives from&quot; relation, within the context model - as specifically denoting when an application data serialization syntax (such as XMI) derives from a more general data serialization syntax (such as XML) though each respective syntax would be organized within a separate branch of the context model.&#10;&#10;Note, furthermore, that in the case of the derivation of XML from SGML, XML also adds features not deriving directly from SGML syntax, such as with XML namespaces." ID="Freemind_Link_111"   COLOR="#000000" BACKGROUND_COLOR="#FFD9B2" STYLE="bubble" ><edge COLOR="#FFD9B2" /><font BOLD="false" ITALIC="false" SIZE="14"/><attribute NAME="Callout" VALUE="{945, -30}"/></node>
</node>
<node TEXT="SGML" ID="Freemind_Link_112"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /></node>
</node>
<node TEXT="Modeling Languages" ID="Freemind_Link_113"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /><node TEXT="MDA Diagram Systems&#10;(Non-normative term)" ID="Freemind_Link_114"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /><richcontent TYPE="NOTE"><html><head> </head><body><p>An MDA diagram system, in the sense denoted within this context model, provides a visual model, an MOF metamodel, and a UML profile, for integration within systems diagram methodologies.</p>
</body></html></richcontent><node TEXT="UML Diagram System" ID="Freemind_Link_115"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /><arrowlink COLOR="#477DB2" DESTINATION="Freemind_Link_123" ENDARROW="Default" ENDINCLINATION="22;0;" ID="Arrow_ID_260" STARTARROW="None" STARTINCLINATION="22;0;" SOURCE_LABEL="" MIDDLE_LABEL="provides  MOF metamodel" TARGET_LABEL="" /><arrowlink COLOR="#477DB2" DESTINATION="Freemind_Link_134" ENDARROW="Default" ENDINCLINATION="22;0;" ID="Arrow_ID_261" STARTARROW="None" STARTINCLINATION="22;0;" SOURCE_LABEL="" MIDDLE_LABEL="provides UML profile" TARGET_LABEL="" /></node>
<node TEXT="SysML Diagram System" ID="Freemind_Link_116"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /><arrowlink COLOR="#477DB2" DESTINATION="Freemind_Link_124" ENDARROW="Default" ENDINCLINATION="22;0;" ID="Arrow_ID_262" STARTARROW="None" STARTINCLINATION="22;0;" SOURCE_LABEL="" MIDDLE_LABEL="provides MOF metamodel" TARGET_LABEL="" /><arrowlink COLOR="#477DB2" DESTINATION="Freemind_Link_135" ENDARROW="Default" ENDINCLINATION="22;0;" ID="Arrow_ID_263" STARTARROW="None" STARTINCLINATION="22;0;" SOURCE_LABEL="" MIDDLE_LABEL="provides UML profile" TARGET_LABEL="" /></node>
<node TEXT="SoaML Diagram System" ID="Freemind_Link_117"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /><arrowlink COLOR="#477DB2" DESTINATION="Freemind_Link_125" ENDARROW="Default" ENDINCLINATION="22;0;" ID="Arrow_ID_264" STARTARROW="None" STARTINCLINATION="22;0;" SOURCE_LABEL="" MIDDLE_LABEL=" provides MOF metamodel" TARGET_LABEL="" /><arrowlink COLOR="#477DB2" DESTINATION="Freemind_Link_136" ENDARROW="Default" ENDINCLINATION="22;0;" ID="Arrow_ID_265" STARTARROW="None" STARTINCLINATION="22;0;" SOURCE_LABEL="" MIDDLE_LABEL="provides UML profile" TARGET_LABEL="" /></node>
</node>
<node TEXT="MDA Modeling Languages" ID="Freemind_Link_118"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /><node TEXT="MOF" ID="Freemind_Link_119"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /><node TEXT="EMOF" ID="Freemind_Link_120"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /></node>
<node TEXT="CMOF" ID="Freemind_Link_121"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /></node>
<node TEXT="MOF Metamodels" ID="Freemind_Link_122"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /><node TEXT="UML Metamodel" ID="Freemind_Link_123"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /></node>
<node TEXT="SysML Metamodel" ID="Freemind_Link_124"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /></node>
<node TEXT="(SysML Metamode)" ID="Freemind_Link_125"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /></node>
<node TEXT="This area needs further research, as for the detailed relations of metamodels and (e.g) UML profiles.&#10;&#10;In one exact question: Is it possible to model a BPMN diagram with a UML profile? (A: Yes. The OMG publishes an albeit non-normative UML profile for BPMN, as well as for each of SysML and SOAML)" ID="Freemind_Link_126"   COLOR="#000000" BACKGROUND_COLOR="#FFD9B2" STYLE="bubble" ><edge COLOR="#FFD9B2" /><font BOLD="false" ITALIC="false" SIZE="14"/><attribute NAME="Callout" VALUE="{687, 465}"/></node>
</node>
</node>
<node TEXT="???" ID="Freemind_Link_127"   COLOR="#000000" BACKGROUND_COLOR="#FFD9B2" STYLE="bubble" ><edge COLOR="#FFD9B2" /><node TEXT="ECore" ID="Freemind_Link_128"   COLOR="#000000" BACKGROUND_COLOR="#FFD9B2" STYLE="bubble" ><edge COLOR="#FFD9B2" /><node TEXT="EMF" ID="Freemind_Link_129"   COLOR="#000000" BACKGROUND_COLOR="#FFD9B2" STYLE="bubble" ><edge COLOR="#FFD9B2" /><node TEXT="Compatibility with EMF may serve to ensure, transitively, compatibility with Eclipse modeling components such as Grafiti" ID="Freemind_Link_130"   COLOR="#000000" BACKGROUND_COLOR="#FFD9B2" STYLE="bubble" ><edge COLOR="#FFD9B2" /><attribute NAME="Callout" VALUE="{382, 22}"/></node>
</node>
<node TEXT="See also: &quot;Relationship between EMF and MOF/UML&quot;, Eclipse Community Forums (11 April, 2003) (at link)" ID="Freemind_Link_131" LINK="http://www.eclipse.org/forums/index.php/m/377329/"  COLOR="#000000" BACKGROUND_COLOR="#FFD9B2" STYLE="bubble" ><edge COLOR="#FFD9B2" /><attribute NAME="Callout" VALUE="{252, 129}"/></node>
</node>
</node>
<node TEXT="OCL" ID="Freemind_Link_132"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /></node>
</node>
<node TEXT="UML Profiles" ID="Freemind_Link_133"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /><node TEXT="UML&#10;(UML Profile)" ID="Freemind_Link_134"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /></node>
<node TEXT="SysML Profile" ID="Freemind_Link_135"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /></node>
<node TEXT="SoaML Profile" ID="Freemind_Link_136"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /></node>
</node>
<node TEXT="OWL" ID="Freemind_Link_137"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /><node TEXT="OWL Syntaxes" ID="Freemind_Link_138"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /><node TEXT="OWL XML Syntax" ID="Freemind_Link_139"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /><arrowlink COLOR="#477DB2" DESTINATION="Freemind_Link_110" ENDARROW="Default" ENDINCLINATION="22;0;" ID="Arrow_ID_266" STARTARROW="None" STARTINCLINATION="22;0;" SOURCE_LABEL="" MIDDLE_LABEL="Derives From" TARGET_LABEL="" /></node>
<node TEXT="OWL Functional Syntax" ID="Freemind_Link_140"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /></node>
<node TEXT="OWL Manchester Syntax" ID="Freemind_Link_141"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /></node>
<node TEXT="OWL RDF Syntaxes" ID="Freemind_Link_142"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /><arrowlink COLOR="#477DB2" DESTINATION="Freemind_Link_147" ENDARROW="Default" ENDINCLINATION="22;0;" ID="Arrow_ID_267" STARTARROW="None" STARTINCLINATION="22;0;" SOURCE_LABEL="" MIDDLE_LABEL="Pertains too" TARGET_LABEL="" /><node TEXT="OWL RDF XML Syntax" ID="Freemind_Link_143"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /><arrowlink COLOR="#477DB2" DESTINATION="Freemind_Link_149" ENDARROW="Default" ENDINCLINATION="22;0;" ID="Arrow_ID_268" STARTARROW="None" STARTINCLINATION="22;0;" SOURCE_LABEL="" MIDDLE_LABEL="Derives From" TARGET_LABEL="" /></node>
<node TEXT="OWL in N3" ID="Freemind_Link_144"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /><arrowlink COLOR="#477DB2" DESTINATION="Freemind_Link_150" ENDARROW="Default" ENDINCLINATION="22;0;" ID="Arrow_ID_269" STARTARROW="None" STARTINCLINATION="22;0;" SOURCE_LABEL="" MIDDLE_LABEL="Derives From" TARGET_LABEL="" /></node>
<node TEXT="OWL in Turtle" ID="Freemind_Link_145"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /><arrowlink COLOR="#477DB2" DESTINATION="Freemind_Link_151" ENDARROW="Default" ENDINCLINATION="22;0;" ID="Arrow_ID_270" STARTARROW="None" STARTINCLINATION="22;0;" SOURCE_LABEL="" MIDDLE_LABEL="Derives From" TARGET_LABEL="" /></node>
</node>
</node>
<node TEXT="OWL is represented here as comprising an ontology modeling language" ID="Freemind_Link_146"   COLOR="#000000" BACKGROUND_COLOR="#FFD9B2" STYLE="bubble" ><edge COLOR="#FFD9B2" /><attribute NAME="Callout" VALUE="{-313, 83}"/></node>
</node>
<node TEXT="RDF" ID="Freemind_Link_147"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /><node TEXT="RDF Syntaxes" ID="Freemind_Link_148"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /><node TEXT="RDF XML Syntax" ID="Freemind_Link_149"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /><arrowlink COLOR="#477DB2" DESTINATION="Freemind_Link_110" ENDARROW="Default" ENDINCLINATION="22;0;" ID="Arrow_ID_271" STARTARROW="None" STARTINCLINATION="22;0;" SOURCE_LABEL="" MIDDLE_LABEL="Derives From" TARGET_LABEL="" /></node>
<node TEXT="N3" ID="Freemind_Link_150"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /></node>
<node TEXT="Turtle" ID="Freemind_Link_151"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /></node>
</node>
</node>
<node TEXT="This context area poses a challenge for the single-axial model. &#10;&#10;Consider that a SysML profile is both a SysML profile and a UML profile, simultaneously.&#10;&#10;It would seem that MOF and UML together form essentially the &quot;backbone&quot; for the modeling components of OMG MDA. As far as the question of whether a diagram tool implementer should select a modeling system's metamodel or respective UML profile for implementation and  support, it would probably be a question of how the modeling tool would be used - whether in a broader sense, with the modeling system's metamodel, or with existing UML tools, as with the respective UML profile.&#10;&#10;As far as the question of whether a model system developer would develop a UML profile and/or an MOF metamodel for the diagram system, it may likewise be a question of context of use. A UML profile may support a more simple mode of integration with existing UML modeling tools, whereas an MOF metamodel may require more extensive work for integration with existing modeling tools.&#10;&#10;The phrase, &quot;Extends,&quot; may be used as a synonym of the phrase, &quot;Derives from,&quot; in a similar sense." ID="Freemind_Link_152"   COLOR="#000000" BACKGROUND_COLOR="#FFD9B2" STYLE="bubble" ><edge COLOR="#FFD9B2" /><font BOLD="false" ITALIC="false" SIZE="14"/><attribute NAME="Callout" VALUE="{-873, 789}"/></node>
</node>
</node>
<node TEXT="Software Tools" ID="Freemind_Link_153"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /><node TEXT="Modeling Tools" ID="Freemind_Link_154"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /><node TEXT="Modeling Tools (Desktop Platform)" ID="Freemind_Link_155"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /><node TEXT="Modelio" ID="Freemind_Link_156"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /></node>
<node TEXT="Cubetto" ID="Freemind_Link_157"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /></node>
</node>
<node TEXT="Modeling Tools (Mobile Platform)" ID="Freemind_Link_158"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /><node TEXT="Cubetto" ID="Freemind_Link_159"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /></node>
</node>
<node TEXT="Modeling Tools (Web Based)" ID="Freemind_Link_160"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /><node TEXT="Web Based BPMN Modeling Tools" ID="Freemind_Link_161"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /><node TEXT="BOS" ID="Freemind_Link_162"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /></node>
<node TEXT="Aperte Workflow " ID="Freemind_Link_163"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /></node>
<node TEXT="Activiti" ID="Freemind_Link_164"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /></node>
</node>
</node>
</node>
</node>
</node>
<node TEXT="Project Management Methodologies" ID="Freemind_Link_165"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /><node TEXT="Agile Methods" ID="Freemind_Link_166"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /><node TEXT="eXtreme Programming (XP)" ID="Freemind_Link_167"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /><node TEXT="See also" ID="Freemind_Link_168"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /><node TEXT="Select Business Solutions. &quot;What is Extreme Programming? (XP)&quot;. Acc. 26 May 2013" ID="Freemind_Link_169"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /></node>
</node>
</node>
<node TEXT="Scrum Methodology" ID="Freemind_Link_170"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /><node TEXT="See Also" ID="Freemind_Link_171"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /><node TEXT="Rawsthorne, Doug and Shimp, Dan. Exploring Scrum. 2011&#10;(Book)" ID="Freemind_Link_172" LINK="http://www.goodreads.com/book/show/12251490"  COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /></node>
<node TEXT="Scrum Alliance&#10;(Organization)" ID="Freemind_Link_173" LINK="http://scrumalliance.org/"  COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /></node>
</node>
</node>
<node TEXT="The &quot;Making Ideas Happen&quot; Methodology" ID="Freemind_Link_174"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /><node TEXT="Developed by Scott Belsky" ID="Freemind_Link_175"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /></node>
<node TEXT="See also" ID="Freemind_Link_176"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /><node TEXT="Belsky, Scott. Making Ideas Happen. 2010&#10;(Book)" ID="Freemind_Link_177" LINK="http://www.goodreads.com/book/show/7696135"  COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /></node>
</node>
<node TEXT="Not per se a formal project management methodology, more a task-oriented approach, geared towards creative work" ID="Freemind_Link_178"   COLOR="#000000" BACKGROUND_COLOR="#FFD9B2" STYLE="bubble" ><edge COLOR="#FFD9B2" /><attribute NAME="Callout" VALUE="{69, 180}"/></node>
</node>
<node TEXT="Other Agile Methods" ID="Freemind_Link_179"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /><node TEXT="See also" ID="Freemind_Link_180"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /><node TEXT="Leonard, Martin. Big Agile Toolkit. 2011&#10;(Book)" ID="Freemind_Link_181" LINK="http://www.goodreads.com/book/show/14401391"  COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /></node>
</node>
</node>
</node>
<node TEXT="This context area should be assigned a work area within the GHub Project, such that would contain the development of the GHub Project's Project Model (PM) Ontology&#10;&#10;(To Do)" ID="Freemind_Link_192"   COLOR="#000000" BACKGROUND_COLOR="#FFD9B2" STYLE="bubble" ><edge COLOR="#FFD9B2" /><attribute NAME="Callout" VALUE="{-3, 167}"/></node>
<node TEXT="Institutional Project Management Methodologies" ID="Freemind_Link_182"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /><node TEXT="Capability Maturity Model (CMM)" ID="Freemind_Link_183"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /><node TEXT="Developed originally by the Software Engineering Institute (SEI)" ID="Freemind_Link_184"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /><arrowlink COLOR="#B27D47" DESTINATION="Freemind_Link_186" ENDARROW="Default" ENDINCLINATION="22;0;" ID="Arrow_ID_272" STARTARROW="None" STARTINCLINATION="22;0;" SOURCE_LABEL="" MIDDLE_LABEL="Reference" TARGET_LABEL="" /></node>
<node TEXT="See also" ID="Freemind_Link_185"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /><node TEXT="Wikipedia. Capability Maturity Model. 19 May 2013. Acc 26 May 2013&#10;(Web Page)" ID="Freemind_Link_186" LINK="http://bit.ly/158MXgT"  COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /></node>
</node>
<node TEXT="Successor" ID="Freemind_Link_187"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /><arrowlink COLOR="#B27D47" DESTINATION="Freemind_Link_191" ENDARROW="Default" ENDINCLINATION="22;0;" ID="Arrow_ID_273" STARTARROW="None" STARTINCLINATION="22;0;" SOURCE_LABEL="" MIDDLE_LABEL="Reference" TARGET_LABEL="" /><node TEXT="CMMI" ID="Freemind_Link_188"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /><node TEXT="See also" ID="Freemind_Link_189"   COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /><node TEXT="CMMI Institute&#10;(Organization)" ID="Freemind_Link_190" LINK="http://www.cmmiinstitute.com/"  COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /></node>
<node TEXT="Select Business Solutions. &quot;What is Capability Maturity Model Integration? (CMMI)&quot;. Acc. 26 May, 2013&#10;(Web Page)" ID="Freemind_Link_191" LINK="http://bit.ly/Z8VtvB"  COLOR="#000000" BACKGROUND_COLOR="#B2B2FE" STYLE="bubble" ><edge COLOR="#B2B2FE" /></node>
</node>
</node>
</node>
</node>
</node>
</node>
</node>
</node>
<node TEXT="This is a proof-of-concept outline, demonstrating components of a context model and components of a project model for the Gazebo Hub Project.&#10;&#10;In some branches, the legibility of relations within the context model approaches zero. It may therefore seem that only a simple context model can be represented interchangeably with a mindmap" ID="Freemind_Link_193"  POSITION="left"  COLOR="#000000" BACKGROUND_COLOR="#FFD9B2" STYLE="bubble" ><edge COLOR="#FFD9B2" /><font BOLD="false" ITALIC="false" SIZE="14"/><attribute NAME="Callout" VALUE="{-121, 278}"/></node>
</node>
</map>